name: Deploy Magic the Gathering Deck Builder to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend # Ensure the workflow operates in the correct directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npx ng build --configuration production --output-path=dist/Magic-Project

      - name: Debug root dir
        run: ls -la

      - name: Debug dist dir
        run: ls -la dist

      - name: Debug dist/Magic-Project
        run: ls -la dist/Magic-Project

      - name: Debug dist/Magic-Project/browser
        run: ls -la dist/Magic-Project/browser

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist/Magic-Project/browser
